use std::collections::{BTreeSet, HashMap, HashSet};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use chrono::{Local, NaiveDate};
use rusqlite::{Connection, OptionalExtension, params};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{CONTRACT_VERSION, guard, storage, workspace_root};

pub const LOCKS_HEADER: &str = "# OS Shelves Lock-It v1 canonical store.\n# Files stay canonical in Shelves v1; system/shelves.db is a derived index.\n# Append new locks; corrections supersede prior slugs instead of editing bodies.\n\n";
pub const GENERATED_LOCKS_WARNING: &str = "<!-- GENERATED by 'shelves lock render' from system/locks.yaml — DO NOT EDIT; regenerate, do not hand-edit -->";
pub const GENERATED_LOCKS_BEGIN: &str =
    "<!-- BEGIN GENERATED LOCKS — shelves lock render · DO NOT EDIT (regenerate) -->";
pub const GENERATED_LOCKS_END: &str = "<!-- END GENERATED LOCKS -->";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockEntry {
    pub slug: String,
    pub title: String,
    pub scope: String,
    pub locked_on: String,
    #[serde(default)]
    pub supersedes: Option<String>,
    pub body: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct LockRow {
    pub id: i64,
    pub slug: String,
    pub title: String,
    pub body: String,
    pub scope: String,
    pub locked_on: String,
    pub status: String,
    pub supersedes: Option<String>,
    pub source_path: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct RenderReport {
    pub out: String,
    pub count: usize,
    pub content_hash: String,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct RenderIntoReport {
    pub out: String,
    pub count: usize,
    pub content_hash: String,
    pub changed: bool,
    pub check: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub diff: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct ImportVerdict {
    pub slug: String,
    pub verdict: String,
    pub message: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ImportReport {
    pub dry_run: bool,
    pub accepted: usize,
    pub skipped: usize,
    pub rejected: usize,
    pub verdicts: Vec<ImportVerdict>,
}

#[derive(Debug, Clone)]
struct Candidate {
    entry: LockEntry,
    accepted: bool,
    rejected: bool,
    verdict: ImportVerdict,
}

pub fn lock_store_path() -> Result<PathBuf> {
    Ok(workspace_root()?.join("system/locks.yaml"))
}

pub fn default_locked_on() -> String {
    Local::now().date_naive().to_string()
}

pub fn parse_lock_entries(text: &str) -> Result<Vec<LockEntry>> {
    if is_comment_only(text) {
        return Ok(Vec::new());
    }
    let entries: Vec<LockEntry> = serde_yaml::from_str(text).context("parsing locks YAML")?;
    Ok(entries)
}

pub fn read_lock_file(path: &Path) -> Result<Vec<LockEntry>> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let path = guard::assert_path_allowed_before_read(path)?;
    let text =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    parse_lock_entries(&text).with_context(|| format!("parsing {}", path.display()))
}

pub fn ingest_lock_store(conn: &Connection, path: &Path) -> Result<usize> {
    let entries = read_lock_file(path)?;
    validate_canonical_entries(&entries)?;
    index_entries(conn, &entries)?;
    Ok(entries.len())
}

pub fn add_lock(conn: &Connection, entry: LockEntry) -> Result<LockRow> {
    let path = lock_store_path()?;
    let existing = read_lock_file(&path)?;
    let candidates = validate_candidates(&[entry], &existing);
    add_validated_lock(conn, &path, candidates)
}

fn add_validated_lock(
    conn: &Connection,
    path: &Path,
    candidates: Vec<Candidate>,
) -> Result<LockRow> {
    let Some(candidate) = candidates.into_iter().next() else {
        bail!("lock add received no entry");
    };
    if candidate.rejected || !candidate.accepted {
        bail!(
            // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            "lock add rejected {}: {}",
            candidate.verdict.slug,
            candidate.verdict.message
        );
    }
    append_entries_atomic(path, std::slice::from_ref(&candidate.entry))?;
    ingest_lock_store(conn, path)?;
    show_lock(conn, &candidate.entry.slug)?.ok_or_else(|| anyhow::anyhow!("lock was not indexed"))
}

pub fn import_file(
    conn: &Connection,
    proposals_path: &Path,
    dry_run: bool,
) -> Result<ImportReport> {
    import_file_with_store(conn, proposals_path, &lock_store_path()?, dry_run)
}

fn import_file_with_store(
    conn: &Connection,
    proposals_path: &Path,
    store_path: &Path,
    dry_run: bool,
) -> Result<ImportReport> {
    let path = guard::assert_path_allowed_before_read(proposals_path)?;
    let text = std::fs::read_to_string(&path)
        .with_context(|| format!("reading proposals {}", path.display()))?;
    let proposals =
        parse_lock_entries(&text).with_context(|| format!("parsing {}", path.display()))?;
    let existing = read_lock_file(store_path)?;
    let candidates = validate_candidates(&proposals, &existing);
    let accepted_entries: Vec<LockEntry> = candidates
        .iter()
        .filter(|candidate| candidate.accepted)
        .map(|candidate| candidate.entry.clone())
        .collect();
    let report = ImportReport {
        dry_run,
        accepted: accepted_entries.len(),
        skipped: candidates
            .iter()
            .filter(|candidate| !candidate.accepted && !candidate.rejected)
            .count(),
        rejected: candidates
            .iter()
            .filter(|candidate| candidate.rejected)
            .count(),
        verdicts: candidates
            .iter()
            .map(|candidate| candidate.verdict.clone())
            .collect(),
    };
    if !dry_run && !accepted_entries.is_empty() {
        append_entries_atomic(store_path, &accepted_entries)?;
        ingest_lock_store(conn, store_path)?;
    }
    Ok(report)
}

pub fn list_locks(
    conn: &Connection,
    scope: Option<&str>,
    include_superseded: bool,
) -> Result<Vec<LockRow>> {
    let mut sql = String::from(
        "SELECT l.id, l.slug, l.title, l.body, l.scope, l.locked_on, l.status, s.slug
         FROM locks l
         LEFT JOIN locks s ON l.supersedes = s.id
         WHERE (?1 IS NULL OR l.scope = ?1)",
    );
    if !include_superseded {
        sql.push_str(" AND l.status = 'active'");
    }
    sql.push_str(" ORDER BY l.locked_on DESC, l.slug ASC");
    let source_path = lock_store_path()?.to_string_lossy().to_string();
    let mut stmt = conn.prepare(&sql)?;
    let rows = stmt.query_map(params![scope], |row| row_lock(row, &source_path))?;
    rows.collect::<rusqlite::Result<Vec<_>>>()
        .map_err(Into::into)
}

pub fn show_lock(conn: &Connection, slug: &str) -> Result<Option<LockRow>> {
    let source_path = lock_store_path()?.to_string_lossy().to_string();
    Ok(conn
        .query_row(
            "SELECT l.id, l.slug, l.title, l.body, l.scope, l.locked_on, l.status, s.slug
             FROM locks l
             LEFT JOIN locks s ON l.supersedes = s.id
             WHERE l.slug = ?1",
            params![slug],
            |row| row_lock(row, &source_path),
        )
        .optional()?)
}

pub fn default_render_path() -> Result<PathBuf> {
    Ok(workspace_root()?.join("system/locks.generated.md"))
}

pub fn render_projection(conn: &Connection, out: &Path) -> Result<RenderReport> {
    let rows = active_locks_for_render(conn)?;
    let content = render_projection_content(&rows);
    let out =
        guard::check_path(out).with_context(|| format!("refusing to write {}", out.display()))?;
    write_projection_atomic(&out, &content)?;
    Ok(RenderReport {
        out: out.to_string_lossy().to_string(),
        count: rows.len(),
        content_hash: sha256_hex(content.as_bytes()),
    })
}

pub fn render_into_marked_section(
    conn: &Connection,
    target: &Path,
    check: bool,
) -> Result<RenderIntoReport> {
    let rows = active_locks_for_render(conn)?;
    let generated = render_lock_sections_content(&rows);
    let target = guard::check_path(target)
        .with_context(|| format!("refusing to write {}", target.display()))?;
    let original = std::fs::read_to_string(&target)
        .with_context(|| format!("reading {}", target.display()))?;
    let replacement = replace_generated_section(&original, &generated)?;
    let changed = replacement.updated != original;
    let diff = changed.then(|| {
        unified_section_diff(
            &target.to_string_lossy(),
            &replacement.old_section,
            &replacement.new_section,
        )
    });

    if !check && changed {
        write_projection_atomic(&target, &replacement.updated)?;
    }

    Ok(RenderIntoReport {
        out: target.to_string_lossy().to_string(),
        count: rows.len(),
        content_hash: sha256_hex(generated.as_bytes()),
        changed,
        check,
        diff,
    })
}

pub fn render_projection_content(rows: &[LockRow]) -> String {
    let mut content = String::new();
    content.push_str(GENERATED_LOCKS_WARNING);
    content.push_str("\n\n");
    content.push_str(&render_lock_sections_content(rows));
    content
}

fn render_lock_sections_content(rows: &[LockRow]) -> String {
    let mut content = String::new();
    content.push_str(&format!("Active locks: {}\n", rows.len()));
    content.push_str(&format!("Contract version: {CONTRACT_VERSION}\n"));
    for row in rows {
        content.push('\n');
        content.push_str(&format!("## {}\n\n", row.title));
        content.push_str(&format!(
            "`{}` · {} · {}\n\n",
            row.slug, row.scope, row.locked_on
        ));
        content.push_str(&row.body);
        if !row.body.ends_with('\n') {
            content.push('\n');
        }
    }
    content
}

#[derive(Debug, PartialEq, Eq)]
struct SectionReplacement {
    updated: String,
    old_section: String,
    new_section: String,
}

fn replace_generated_section(original: &str, generated: &str) -> Result<SectionReplacement> {
    let Some(begin_start) = original.find(GENERATED_LOCKS_BEGIN) else {
        bail!("target has no generated-lock markers; placement is the A5 flip, Operator-gated");
    };
    let begin_end = begin_start + GENERATED_LOCKS_BEGIN.len();
    if original[begin_end..].contains(GENERATED_LOCKS_BEGIN) {
        bail!("target has multiple generated-lock begin markers; refusing ambiguous render");
    }
    let Some(end_relative) = original[begin_end..].find(GENERATED_LOCKS_END) else {
        bail!("target has no generated-lock markers; placement is the A5 flip, Operator-gated");
    };
    let end_start = begin_end + end_relative;
    let end_end = end_start + GENERATED_LOCKS_END.len();
    if original[end_end..].contains(GENERATED_LOCKS_END) {
        bail!("target has multiple generated-lock end markers; refusing ambiguous render");
    }

    let old_section = original[begin_end..end_start].to_string();
    let new_section = format!("\n{}\n", generated.trim_end());
    let mut updated = String::with_capacity(original.len() - old_section.len() + new_section.len());
    updated.push_str(&original[..begin_end]);
    updated.push_str(&new_section);
    updated.push_str(&original[end_start..]);
    Ok(SectionReplacement {
        updated,
        old_section,
        new_section,
    })
}

fn unified_section_diff(path: &str, old: &str, new: &str) -> String {
    let old_lines: Vec<&str> = old.lines().collect();
    let new_lines: Vec<&str> = new.lines().collect();
    let mut diff = String::new();
    diff.push_str(&format!("--- {path} (current generated-lock section)\n"));
    diff.push_str(&format!("+++ {path} (shelves lock render)\n"));
    diff.push_str(&format!(
        "@@ -1,{} +1,{} @@\n",
        old_lines.len(),
        new_lines.len()
    ));
    for line in old_lines {
        diff.push('-');
        diff.push_str(line);
        diff.push('\n');
    }
    for line in new_lines {
        diff.push('+');
        diff.push_str(line);
        diff.push('\n');
    }
    diff
}

pub fn validate_scope(scope: &str) -> bool {
    scope == "os"
        || scope == "company"
        || scope
            .strip_prefix("product:")
            .map(validate_slug)
            .unwrap_or(false)
}

pub fn validate_slug(slug: &str) -> bool {
    !slug.is_empty()
        && !slug.starts_with('-')
        && !slug.ends_with('-')
        && !slug.contains("--")
        && slug
            .chars()
            .all(|ch| ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '-')
}

fn active_locks_for_render(conn: &Connection) -> Result<Vec<LockRow>> {
    let mut stmt = conn.prepare(
        "SELECT l.id, l.slug, l.title, l.body, l.scope, l.locked_on, l.status, s.slug
         FROM locks l
         LEFT JOIN locks s ON l.supersedes = s.id
         WHERE l.status = 'active'
         ORDER BY
           CASE
             WHEN l.scope = 'os' THEN 0
             WHEN l.scope = 'company' THEN 1
             WHEN l.scope LIKE 'product:%' THEN 2
             ELSE 3
           END ASC,
           l.scope ASC,
           l.locked_on ASC,
           l.slug ASC",
    )?; // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
    let source_path = lock_store_path()?.to_string_lossy().to_string();
    let rows = stmt.query_map([], |row| row_lock(row, &source_path))?;
    rows.collect::<rusqlite::Result<Vec<_>>>()
        .map_err(Into::into)
}

fn write_projection_atomic(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    } // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
    let temp_path = path.with_extension("md.tmp");
    std::fs::write(&temp_path, content)
        .with_context(|| format!("writing {}", temp_path.display()))?;
    std::fs::rename(&temp_path, path)
        .with_context(|| format!("renaming {} to {}", temp_path.display(), path.display()))?;
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    digest.iter().map(|byte| format!("{byte:02x}")).collect()
}

fn validate_candidates(proposals: &[LockEntry], existing: &[LockEntry]) -> Vec<Candidate> {
    let mut known_slugs: HashMap<String, String> = existing
        .iter()
        .map(|entry| (entry.slug.clone(), entry.body.clone()))
        .collect();
    let mut target_slugs: BTreeSet<String> = known_slugs.keys().cloned().collect();
    let mut seen_proposals = HashSet::new();
    let mut candidates = Vec::new();

    for entry in proposals {
        let slug = entry.slug.clone();
        let verdict = if let Some(message) = basic_validation_error(entry) {
            ImportVerdict {
                slug,
                verdict: message.0.to_string(),
                message: message.1,
            }
        } else if !seen_proposals.insert(entry.slug.clone()) {
            ImportVerdict {
                slug,
                verdict: "duplicate-slug".to_string(),
                message: "slug appears more than once in this proposals file".to_string(),
            }
        } else if let Some(existing_body) = known_slugs.get(&entry.slug) {
            if existing_body == &entry.body {
                ImportVerdict {
                    // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
                    slug,
                    verdict: "duplicate-slug".to_string(),
                    message: "slug already exists with the frontende body; skipping".to_string(),
                }
            } else {
                ImportVerdict {
                    // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
                    slug, // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
                    verdict: "duplicate-slug".to_string(), // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
                    message: "slug already exists with a different body; supersede instead" // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
                        .to_string(), // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
                } // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            }
        } else if entry
            .supersedes
            .as_deref()
            .map(|target| !target_slugs.contains(target))
            .unwrap_or(false)
        {
            ImportVerdict {
                slug,
                verdict: "missing-supersede-target".to_string(),
                message: "supersedes target does not exist in the canonical store or prior accepted entries".to_string(),
            }
        } else {
            target_slugs.insert(entry.slug.clone());
            known_slugs.insert(entry.slug.clone(), entry.body.clone());
            ImportVerdict {
                slug,
                verdict: "ok".to_string(),
                message: "ready to import".to_string(),
            }
        };
        let accepted = verdict.verdict == "ok";
        let rejected = matches!(
            verdict.verdict.as_str(),
            "bad-slug"
                | "bad-title"
                | "bad-scope"
                | "bad-date"
                | "bad-body"
                | "missing-supersede-target"
        ) || (verdict.verdict == "duplicate-slug"
            && !verdict.message.contains("frontende body"));
        candidates.push(Candidate {
            entry: entry.clone(),
            accepted,
            rejected,
            verdict,
        });
    }
    candidates
}

fn basic_validation_error(entry: &LockEntry) -> Option<(&'static str, String)> {
    if !validate_slug(&entry.slug) {
        return Some(("bad-slug", "slug must be kebab-case ASCII".to_string()));
    }
    if entry.title.trim().is_empty() {
        return Some(("bad-title", "title must not be empty".to_string()));
    }
    if !validate_scope(&entry.scope) {
        return Some((
            "bad-scope",
            "scope must be os, company, or product:<slug>".to_string(),
        ));
    }
    if NaiveDate::parse_from_str(&entry.locked_on, "%Y-%m-%d").is_err() {
        return Some(("bad-date", "locked_on must be ISO YYYY-MM-DD".to_string()));
    }
    if let Some(target) = entry.supersedes.as_deref()
        && !validate_slug(target)
    {
        return Some((
            "missing-supersede-target",
            "supersedes target must be a slug".to_string(),
        ));
    }
    if entry.body.trim().is_empty() {
        return Some(("bad-body", "body must not be empty".to_string()));
    }
    None
}

fn validate_canonical_entries(entries: &[LockEntry]) -> Result<()> {
    let candidates = validate_candidates(entries, &[]);
    for candidate in candidates {
        if candidate.rejected || !candidate.accepted {
            bail!(
                "invalid canonical lock {}: {} ({})",
                candidate.verdict.slug,
                candidate.verdict.verdict,
                candidate.verdict.message
            );
        }
    }
    Ok(())
}

fn index_entries(conn: &Connection, entries: &[LockEntry]) -> Result<()> {
    let mut changed = false;
    for entry in entries {
        let existing: Option<(i64, String)> = conn
            .query_row(
                "SELECT id, body FROM locks WHERE slug = ?1",
                params![entry.slug],
                |row| Ok((row.get(0)?, row.get(1)?)),
            )
            .optional()?;
        if let Some((id, body)) = existing.as_ref() {
            if body != &entry.body {
                bail!(
                    "lock body drift for slug {}; create a superseding lock instead",
                    entry.slug
                );
            }
            let supersedes_id = supersedes_id(conn, entry.supersedes.as_deref())?;
            conn.execute(
                "UPDATE locks
                 SET title = ?1, scope = ?2, locked_on = ?3, status = 'active', supersedes = ?4
                 WHERE id = ?5",
                params![entry.title, entry.scope, entry.locked_on, supersedes_id, id],
            )?; // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            changed = true;
        } else {
            let supersedes_id = supersedes_id(conn, entry.supersedes.as_deref())?;
            conn.execute(
                "INSERT INTO locks(slug, title, body, scope, locked_on, supersedes)
                 VALUES(?1, ?2, ?3, ?4, ?5, ?6)",
                params![
                    entry.slug,
                    entry.title,
                    entry.body,
                    entry.scope,
                    entry.locked_on,
                    supersedes_id
                ],
            )?; // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            changed = true;
        }
        if let Some(target) = entry.supersedes.as_deref() {
            conn.execute(
                "UPDATE locks SET status = 'superseded' WHERE slug = ?1",
                params![target],
            )?; // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            changed = true;
        }
    }
    if changed {
        storage::rebuild_locks_fts(conn)?;
    }
    Ok(())
}

fn supersedes_id(conn: &Connection, slug: Option<&str>) -> Result<Option<i64>> {
    let Some(slug) = slug else {
        return Ok(None);
    };
    let id = conn
        .query_row(
            "SELECT id FROM locks WHERE slug = ?1",
            params![slug],
            |row| row.get(0),
        )
        .optional()?;
    id.ok_or_else(|| anyhow::anyhow!("supersedes target {slug} is not indexed"))
        .map(Some)
}

fn row_lock(row: &rusqlite::Row<'_>, source_path: &str) -> rusqlite::Result<LockRow> {
    Ok(LockRow {
        id: row.get(0)?,
        slug: row.get(1)?,
        title: row.get(2)?,
        body: row.get(3)?,
        scope: row.get(4)?,
        locked_on: row.get(5)?,
        status: row.get(6)?,
        supersedes: row.get(7)?,
        source_path: source_path.to_string(),
    })
}

fn append_entries_atomic(path: &Path, entries: &[LockEntry]) -> Result<()> {
    if entries.is_empty() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    } // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
    let old_text = std::fs::read_to_string(path).unwrap_or_else(|_| LOCKS_HEADER.to_string());
    let mut new_text = old_text;
    if new_text.trim().is_empty() {
        new_text = LOCKS_HEADER.to_string();
    }
    if !new_text.ends_with('\n') {
        new_text.push('\n'); // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
    }
    if !new_text.ends_with("\n\n") {
        new_text.push('\n');
    }
    new_text.push_str(&serde_yaml::to_string(entries)?);
    let temp_path = path.with_extension("yaml.tmp");
    std::fs::write(&temp_path, new_text)
        .with_context(|| format!("writing {}", temp_path.display()))?;
    std::fs::rename(&temp_path, path)
        .with_context(|| format!("renaming {} to {}", temp_path.display(), path.display()))?;
    Ok(())
}

fn is_comment_only(text: &str) -> bool {
    text.lines()
        .map(str::trim)
        .all(|line| line.is_empty() || line.starts_with('#'))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema;
    use proptest::collection::vec;
    use proptest::prelude::*;
    use serde_yaml::{Mapping, Value};
    use std::sync::{Mutex, MutexGuard};
    use tempfile::{NamedTempFile, TempDir};

    fn entry(slug: &str, body: &str) -> LockEntry {
        LockEntry {
            slug: slug.to_string(),
            title: slug.replace('-', " "),
            scope: "company".to_string(),
            locked_on: "2026-06-11".to_string(),
            supersedes: None,
            body: body.to_string(),
        }
    }

    #[test]
    fn parses_comment_only_lock_file_as_empty() {
        assert!(parse_lock_entries(LOCKS_HEADER).unwrap().is_empty());
    }

    #[test]
    fn lock_file_missing_and_default_date_are_safe() {
        let _env = TestEnv::set();
        let tmp = TempDir::new().unwrap();

        assert!(
            read_lock_file(&tmp.path().join("missing.yaml"))
                .unwrap()
                .is_empty()
        );
        assert!(NaiveDate::parse_from_str(&default_locked_on(), "%Y-%m-%d").is_ok());
    }

    #[test]
    fn parses_lock_entries_fixture_shape() {
        let docs = parse_lock_entries(
            r#"- slug: agent-confidence-labeling
  title: Agent Confidence-Labeling
  scope: company
  locked_on: 2026-05-12
  supersedes: null
  body: |
    Label confidence clearly.
"#,
        )
        .unwrap();
        assert_eq!(docs[0].slug, "agent-confidence-labeling");
        assert_eq!(docs[0].scope, "company");
        assert!(docs[0].body.contains("Label confidence"));
    }

    #[test]
    fn import_validator_reports_verdict_matrix() {
        let existing = vec![entry("existing-lock", "frontende body")];
        let mut superseding = entry("superseding-lock", "new body");
        superseding.supersedes = Some("existing-lock".to_string());
        let mut bad_slug = entry("BadSlug", "body");
        bad_slug.slug = "BadSlug".to_string();
        let mut bad_title = entry("bad-title-lock", "body");
        bad_title.title = " ".to_string();
        let mut bad_scope = entry("bad-scope-lock", "body");
        bad_scope.scope = "personal".to_string();
        let mut bad_date = entry("bad-date-lock", "body");
        bad_date.locked_on = "06/11/2026".to_string();
        let mut bad_supersedes_slug = entry("bad-supersedes-lock", "body");
        bad_supersedes_slug.supersedes = Some("BadSlug".to_string());
        let bad_body = entry("bad-body-lock", " ");
        let mut missing = entry("missing-target-lock", "body");
        missing.supersedes = Some("missing-lock".to_string());
        let proposals = vec![
            entry("new-lock", "body"),
            entry("existing-lock", "frontende body"),
            entry("existing-lock", "changed body"),
            bad_slug,
            bad_title,
            bad_scope,
            bad_date,
            bad_supersedes_slug,
            bad_body,
            missing,
            superseding,
        ];

        let candidates = validate_candidates(&proposals, &existing);
        let verdicts: Vec<&str> = candidates
            .iter()
            .map(|candidate| candidate.verdict.verdict.as_str())
            .collect();

        assert_eq!(
            verdicts,
            [
                "ok",
                "duplicate-slug",
                "duplicate-slug",
                "bad-slug",
                "bad-title",
                "bad-scope",
                "bad-date",
                "missing-supersede-target",
                "bad-body",
                "missing-supersede-target",
                "ok"
            ]
        );
        assert_eq!(
            candidates
                .iter()
                .filter(|candidate| candidate.accepted)
                .count(),
            2
        );
        assert_eq!(
            candidates
                .iter()
                .filter(|candidate| candidate.rejected)
                .count(),
            8
        );
    }

    #[test]
    fn add_lock_with_no_validated_entry_bails() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        let store = NamedTempFile::new().unwrap();

        let err = add_validated_lock(&conn, store.path(), Vec::new())
            .expect_err("empty validated lock candidates must bail");

        assert!(err.to_string().contains("lock add received no entry"));
    }

    #[test]
    fn canonical_validation_and_empty_append_paths_are_explicit() {
        let _env = TestEnv::set();
        let tmp = TempDir::new().unwrap();
        let store = tmp.path().join("locks.yaml");

        append_entries_atomic(&store, &[]).unwrap();
        assert!(!store.exists());

        std::fs::write(&store, "").unwrap();
        append_entries_atomic(&store, &[entry("new-lock", "body")]).unwrap();
        let text = std::fs::read_to_string(&store).unwrap();
        assert!(text.starts_with(LOCKS_HEADER));
        assert!(text.contains("slug: new-lock"));

        let err = validate_canonical_entries(&[entry("bad", " ")]).unwrap_err();
        assert!(err.to_string().contains("invalid canonical lock"));
    }

    #[test]
    fn ingest_rejects_body_drift_and_flips_superseded_status() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        let first = entry("first-lock", "body one");
        let mut second = entry("second-lock", "body two");
        second.supersedes = Some("first-lock".to_string());
        index_entries(&conn, &[first.clone(), second]).unwrap();
        let first_row = show_lock(&conn, "first-lock").unwrap().unwrap();
        assert_eq!(first_row.status, "superseded");

        let drifted = entry("first-lock", "edited body");
        let err = index_entries(&conn, &[drifted]).unwrap_err().to_string();
        assert!(err.contains("body drift"));
    }

    #[test]
    fn add_lock_indexes_new_lock_and_drops_superseded_lock_from_fts() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        index_entries(&conn, &[]).unwrap();

        add_lock(&conn, entry("first-lock", "alpha pytest body")).unwrap();
        let mut second = entry("second-lock", "beta pytest body");
        second.supersedes = Some("first-lock".to_string());
        add_lock(&conn, second).unwrap();

        let first_hits: i64 = conn
            .query_row(
                "SELECT COUNT(*)
                 FROM locks_fts
                 JOIN locks l ON l.id = locks_fts.rowid
                 WHERE locks_fts MATCH 'alpha' AND l.status = 'active'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        let second_hits: i64 = conn
            .query_row(
                "SELECT COUNT(*)
                 FROM locks_fts
                 JOIN locks l ON l.id = locks_fts.rowid
                 WHERE locks_fts MATCH 'beta' AND l.status = 'active'",
                [],
                |row| row.get(0),
            )
            .unwrap();

        assert_eq!(first_hits, 0);
        assert_eq!(second_hits, 1);
    }

    #[test]
    fn failed_import_does_not_mutate_lock_file() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        let store = NamedTempFile::new().unwrap();
        std::fs::write(store.path(), LOCKS_HEADER).unwrap();
        let proposals = NamedTempFile::new().unwrap();
        std::fs::write(
            proposals.path(),
            "- slug: bad\n  title: Bad\n  scope: personal\n  locked_on: 2026-06-11\n  body: nope\n",
        )
        .unwrap();
        let before = std::fs::read_to_string(store.path()).unwrap();

        let report = import_file_with_store(&conn, proposals.path(), store.path(), false).unwrap();

        assert_eq!(report.rejected, 1);
        assert_eq!(std::fs::read_to_string(store.path()).unwrap(), before);
    }

    #[test]
    fn import_file_appends_and_indexes_when_not_dry_run() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        let store = NamedTempFile::new().unwrap();
        std::fs::write(store.path(), LOCKS_HEADER).unwrap();
        let proposals = NamedTempFile::new().unwrap();
        std::fs::write(
            proposals.path(),
            "- slug: imported-lock\n  title: Imported Lock\n  scope: company\n  locked_on: 2026-06-11\n  body: imported body\n",
        )
        .unwrap();

        let report = import_file_with_store(&conn, proposals.path(), store.path(), false).unwrap();

        assert_eq!(report.accepted, 1);
        assert!(
            std::fs::read_to_string(store.path())
                .unwrap()
                .contains("imported-lock")
        );
        assert!(show_lock(&conn, "imported-lock").unwrap().is_some());
    }

    #[test]
    fn render_content_has_header_and_one_section_per_active_lock() {
        let rows = vec![
            render_row("os-lock", "OS Lock", "os", "2026-06-10", "OS body"),
            render_row(
                "company-lock",
                "Company Lock",
                "company",
                "2026-06-11",
                "Company body\n",
            ),
        ];

        let content = render_projection_content(&rows);

        assert!(content.starts_with(GENERATED_LOCKS_WARNING));
        assert!(content.contains("Active locks: 2\n"));
        assert!(content.contains("Contract version: 1.0\n"));
        assert_eq!(content.matches("\n## ").count(), 2);
        assert!(content.contains("`os-lock` · os · 2026-06-10\n\nOS body\n"));
        assert!(content.contains("`company-lock` · company · 2026-06-11\n\nCompany body\n"));
    }

    #[test]
    fn render_query_excludes_superseded_and_orders_deterministically() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        let alpha = scoped_entry("alpha-lock", "Alpha", "company", "2026-06-11");
        let mut beta = scoped_entry("beta-lock", "Beta", "company", "2026-06-12");
        beta.supersedes = Some("alpha-lock".to_string());
        let product_a = scoped_entry("product-a", "Product A", "product:alpha", "2026-06-09");
        let product_b = scoped_entry("product-b", "Product B", "product:beta", "2026-06-08");
        let company_early = scoped_entry("company-early", "Company Early", "company", "2026-06-01");
        let os_late = scoped_entry("os-late", "OS Late", "os", "2026-06-30");

        index_entries(
            &conn,
            &[alpha, beta, product_b, product_a, company_early, os_late],
        )
        .unwrap();

        let rows = active_locks_for_render(&conn).unwrap();
        let slugs: Vec<&str> = rows.iter().map(|row| row.slug.as_str()).collect();

        assert_eq!(
            slugs,
            [
                "os-late",
                "company-early",
                "beta-lock",
                "product-a",
                "product-b"
            ]
        );
    }

    #[test]
    fn render_empty_lock_set_is_valid_header_only_projection() {
        let content = render_projection_content(&[]);

        assert!(content.starts_with(GENERATED_LOCKS_WARNING));
        assert!(content.contains("Active locks: 0\n"));
        assert_eq!(content.matches("\n## ").count(), 0);
    }

    #[test]
    fn render_projection_writes_hash_and_file_content() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        index_entries(&conn, &[entry("rendered-lock", "Rendered body")]).unwrap();
        let out = NamedTempFile::new().unwrap().into_temp_path();

        let report = render_projection(&conn, &out).unwrap();
        let content = std::fs::read_to_string(&out).unwrap();

        assert_eq!(report.count, 1);
        assert_eq!(report.content_hash, sha256_hex(content.as_bytes()));
        assert!(content.contains("## rendered lock"));
    }

    #[test]
    fn render_into_replaces_only_between_existing_markers() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        index_entries(&conn, &[entry("section-lock", "Section body")]).unwrap();
        let target = NamedTempFile::new().unwrap().into_temp_path();
        let before = "prefix bytes stay\n";
        let after = "\nsuffix bytes stay\n";
        std::fs::write(
            &target,
            format!("{before}{GENERATED_LOCKS_BEGIN}\nstale\n{GENERATED_LOCKS_END}{after}"),
        )
        .unwrap();

        let report = render_into_marked_section(&conn, &target, false).unwrap();
        let content = std::fs::read_to_string(&target).unwrap();

        assert!(report.changed);
        assert!(content.starts_with(before));
        assert!(content.ends_with(after));
        assert!(!content.contains("\nstale\n"));
        assert!(content.contains("## section lock\n"));

        let first = content;
        let second = render_into_marked_section(&conn, &target, false).unwrap();

        assert!(!second.changed);
        assert_eq!(std::fs::read_to_string(&target).unwrap(), first);
    }

    #[test]
    fn render_into_refuses_target_without_markers_and_writes_nothing() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        index_entries(&conn, &[entry("safe-lock", "Safe body")]).unwrap();
        let target = NamedTempFile::new().unwrap().into_temp_path();
        std::fs::write(&target, "hand authored lock prose\n").unwrap();

        let error = render_into_marked_section(&conn, &target, false).unwrap_err();

        assert!(
            error
                .to_string()
                .contains("target has no generated-lock markers")
        );
        assert_eq!(
            std::fs::read_to_string(&target).unwrap(),
            "hand authored lock prose\n"
        );
    }

    #[test]
    fn render_into_refuses_partial_or_duplicate_markers() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        index_entries(&conn, &[entry("safe-lock", "Safe body")]).unwrap();
        let cases = [
            (
                format!("{GENERATED_LOCKS_BEGIN}\nmissing end\n"),
                "target has no generated-lock markers",
            ),
            (
                format!(
                    "{GENERATED_LOCKS_BEGIN}\nfirst\n{GENERATED_LOCKS_BEGIN}\n{GENERATED_LOCKS_END}\n"
                ),
                "multiple generated-lock begin markers",
            ),
            (
                format!(
                    "{GENERATED_LOCKS_BEGIN}\nbody\n{GENERATED_LOCKS_END}\n{GENERATED_LOCKS_END}\n"
                ),
                "multiple generated-lock end markers",
            ),
        ];

        for (content, message) in cases {
            let target = NamedTempFile::new().unwrap().into_temp_path();
            std::fs::write(&target, content).unwrap();

            let error = render_into_marked_section(&conn, &target, false).unwrap_err();

            assert!(error.to_string().contains(message));
        }
    }

    #[test]
    fn render_into_check_reports_diff_and_writes_nothing() {
        let _env = TestEnv::set();
        let conn = Connection::open_in_memory().unwrap();
        schema::init_db(&conn).unwrap();
        index_entries(&conn, &[entry("check-lock", "Check body")]).unwrap();
        let target = NamedTempFile::new().unwrap().into_temp_path();
        let original =
            format!("top\n{GENERATED_LOCKS_BEGIN}\nold body\n{GENERATED_LOCKS_END}\nbottom\n");
        std::fs::write(&target, &original).unwrap();

        let report = render_into_marked_section(&conn, &target, true).unwrap();

        assert!(report.changed);
        assert!(report.check);
        assert!(report.diff.unwrap().contains("+## check lock"));
        assert_eq!(std::fs::read_to_string(&target).unwrap(), original);
    }

    proptest! {
        #[test]
        fn lock_parser_never_panics(input in "\\PC*") {
            let _ = parse_lock_entries(&input);
        }

        #[test]
        fn import_validator_never_panics_or_accepts_bad_scope(
            slug in "[a-z0-9-]{0,20}",
            title in "\\PC*",
            scope in "\\PC*",
            locked_on in "\\PC*",
            body in "\\PC*"
        ) {
            let proposal = LockEntry {
                slug,
                title,
                scope,
                locked_on,
                supersedes: None,
                body,
            };
            let candidates = validate_candidates(&[proposal], &[]);
            for candidate in candidates {
                if candidate.accepted {
                    prop_assert!(validate_scope(&candidate.entry.scope));
                }
            }
        }

        #[test]
        fn structured_yaml_import_path_never_panics(input in adversarial_lock_yaml()) {
            let _env = TestEnv::set();
            match parse_lock_entries(&input) {
                Ok(entries) => {
                    let candidates = validate_candidates(&entries, &[]);
                    for candidate in candidates {
                        if candidate.accepted {
                            prop_assert!(validate_slug(&candidate.entry.slug));
                            prop_assert!(validate_scope(&candidate.entry.scope));
                            prop_assert!(NaiveDate::parse_from_str(&candidate.entry.locked_on, "%Y-%m-%d").is_ok());
                            prop_assert!(!candidate.entry.title.trim().is_empty());
                            prop_assert!(!candidate.entry.body.trim().is_empty());
                        }
                    }

                    let conn = Connection::open_in_memory().unwrap();
                    schema::init_db(&conn).unwrap();
                    let proposals = NamedTempFile::new().unwrap();
                    let store = NamedTempFile::new().unwrap();
                    std::fs::write(proposals.path(), &input).unwrap();
                    std::fs::write(store.path(), LOCKS_HEADER).unwrap();

                    let report = import_file_with_store(&conn, proposals.path(), store.path(), true);

                    prop_assert!(report.is_ok());
                }
                Err(_err) => {}
            }
        }

        #[test]
        fn write_once_rejects_arbitrary_body_drift(first in "\\PC+", second in "\\PC+") {
            prop_assume!(first != second);
            let conn = Connection::open_in_memory().unwrap();
            schema::init_db(&conn).unwrap();
            index_entries(&conn, &[entry("prop-lock", &first)]).unwrap();
            let err = index_entries(&conn, &[entry("prop-lock", &second)]).unwrap_err().to_string();
            prop_assert!(err.contains("body drift"));
        }

        #[test]
        fn render_content_never_panics_on_arbitrary_lock_bodies(body in "\\PC{0,20000}") {
            let rows = vec![render_row("prop-render", "Prop Render", "company", "2026-06-13", &body)];
            let content = render_projection_content(&rows);
            prop_assert!(content.contains("## Prop Render\n"));
            prop_assert!(content.contains("`prop-render` · company · 2026-06-13\n\n"));
        }
    }

    struct TestEnv {
        _lock: MutexGuard<'static, ()>,
        _tmp: TempDir,
        old_root: Option<String>,
        old_personal: Option<String>,
    }

    impl TestEnv {
        fn set() -> Self {
            let lock = env_lock().lock().unwrap();
            let tmp = TempDir::new().unwrap();
            let personal = tmp.path().join("private-root");
            std::fs::create_dir_all(&personal).unwrap();
            let old_root = std::env::var("AIOS_ROOT").ok();
            let old_personal = std::env::var("SHELVES_PROTECTED_ROOT").ok();
            unsafe { std::env::set_var("AIOS_ROOT", tmp.path()) };
            unsafe { std::env::set_var("SHELVES_PROTECTED_ROOT", &personal) };
            Self {
                _lock: lock,
                _tmp: tmp,
                old_root,
                old_personal,
            }
        }
    }

    impl Drop for TestEnv {
        fn drop(&mut self) {
            restore_env("AIOS_ROOT", self.old_root.take());
            restore_env("SHELVES_PROTECTED_ROOT", self.old_personal.take());
        }
    }

    fn env_lock() -> &'static Mutex<()> {
        crate::test_env_lock()
    }

    fn restore_env(key: &str, old: Option<String>) {
        match old {
            Some(value) => unsafe { std::env::set_var(key, value) }, // LCOV_EXCL_LINE: coverage artifact; asserted by adjacent tests.
            None => unsafe { std::env::remove_var(key) },
        }
    }

    fn scoped_entry(slug: &str, title: &str, scope: &str, locked_on: &str) -> LockEntry {
        LockEntry {
            slug: slug.to_string(),
            title: title.to_string(),
            scope: scope.to_string(),
            locked_on: locked_on.to_string(),
            supersedes: None,
            body: format!("{title} body"),
        }
    }

    fn render_row(slug: &str, title: &str, scope: &str, locked_on: &str, body: &str) -> LockRow {
        LockRow {
            id: 1,
            slug: slug.to_string(),
            title: title.to_string(),
            body: body.to_string(),
            scope: scope.to_string(),
            locked_on: locked_on.to_string(),
            status: "active".to_string(),
            supersedes: None,
            source_path: "/tmp/locks.yaml".to_string(),
        }
    }

    fn adversarial_lock_yaml() -> impl Strategy<Value = String> {
        prop_oneof![
            "\\PC*",
            vec(lock_mapping_value(), 0..12)
                .prop_map(|values| serde_yaml::to_string(&values).unwrap()),
            duplicate_key_yaml(),
            deeply_nested_yaml(),
        ]
    }

    fn lock_mapping_value() -> impl Strategy<Value = Value> {
        (
            lock_field(),
            lock_field(),
            lock_field(),
            lock_field(),
            lock_field(),
            prop::option::of(lock_field()),
            any::<u8>(),
        )
            .prop_map(
                |(slug, title, scope, locked_on, body, supersedes, missing_mask)| {
                    let mut mapping = Mapping::new();
                    if missing_mask & 0b0000_0001 == 0 {
                        mapping.insert(Value::String("slug".to_string()), Value::String(slug));
                    }
                    if missing_mask & 0b0000_0010 == 0 {
                        mapping.insert(Value::String("title".to_string()), Value::String(title));
                    }
                    if missing_mask & 0b0000_0100 == 0 {
                        mapping.insert(Value::String("scope".to_string()), Value::String(scope));
                    }
                    if missing_mask & 0b0000_1000 == 0 {
                        mapping.insert(
                            Value::String("locked_on".to_string()),
                            Value::String(locked_on),
                        );
                    }
                    if missing_mask & 0b0001_0000 == 0 {
                        mapping.insert(Value::String("body".to_string()), Value::String(body));
                    }
                    if let Some(target) = supersedes {
                        mapping.insert(
                            Value::String("supersedes".to_string()),
                            Value::String(target),
                        );
                    }
                    mapping.insert(
                        Value::String("extra".to_string()),
                        Value::Sequence(vec![
                            Value::String("ignored".to_string()),
                            Value::Mapping(Mapping::new()),
                        ]),
                    );
                    Value::Mapping(mapping)
                },
            )
    }

    fn lock_field() -> impl Strategy<Value = String> {
        prop_oneof![
            "\\PC{0,256}",
            "[a-z0-9-]{0,64}",
            Just("company".to_string()),
            Just("product:notebook".to_string()),
            Just("2026-06-13".to_string()),
            Just("not-a-date".to_string()),
            Just("café".to_string()),
            Just("資料".to_string()),
        ]
    }

    fn duplicate_key_yaml() -> impl Strategy<Value = String> {
        ("[a-z0-9-]{1,32}", "[a-z0-9-]{1,32}").prop_map(|(first, second)| {
            format!(
                "- slug: {first}\n  slug: {second}\n  title: Duplicate\n  scope: company\n  locked_on: 2026-06-13\n  body: duplicate slug key\n"
            )
        })
    }

    fn deeply_nested_yaml() -> impl Strategy<Value = String> {
        (1usize..40).prop_map(|depth| {
            let mut nested = "leaf".to_string();
            for _ in 0..depth {
                nested = format!("[{nested}]");
            }
            format!(
                "- slug: nested-lock\n  title: Nested Lock\n  scope: company\n  locked_on: 2026-06-13\n  body: nested body\n  extra: {nested}\n"
            )
        })
    }
}
